"""update task model for reporting

Revision ID: 96ae9810d3ae
Revises: d4e5f6a7b8c9
Create Date: 2026-05-22 10:57:22.472533

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '96ae9810d3ae'
down_revision: Union[str, Sequence[str], None] = 'd4e5f6a7b8c9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('project_name', sa.String(), nullable=True))
    op.add_column('tasks', sa.Column('worked_hours', sa.Float(), nullable=True))
    op.add_column('tasks', sa.Column('is_recurring', sa.Boolean(), nullable=True))
    op.add_column('tasks', sa.Column('recurring_type', sa.String(), nullable=True))
    op.add_column('tasks', sa.Column('last_activity_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('tasks', sa.Column('reminder_sent', sa.Boolean(), nullable=True))
    op.add_column('tasks', sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('tasks', sa.Column('blocked_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('tasks', sa.Column('overdue_at', sa.DateTime(timezone=True), nullable=True))
    op.alter_column('tasks', 'task_type',
               existing_type=sa.VARCHAR(),
               nullable=True,
               existing_server_default=sa.text("'personal'::character varying"))
    op.alter_column('tasks', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tasks', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('tasks', 'task_type',
               existing_type=sa.VARCHAR(),
               nullable=False,
               existing_server_default=sa.text("'personal'::character varying"))
    op.drop_column('tasks', 'overdue_at')
    op.drop_column('tasks', 'blocked_at')
    op.drop_column('tasks', 'completed_at')
    op.drop_column('tasks', 'reminder_sent')
    op.drop_column('tasks', 'last_activity_at')
    op.drop_column('tasks', 'recurring_type')
    op.drop_column('tasks', 'is_recurring')
    op.drop_column('tasks', 'worked_hours')
    op.drop_column('tasks', 'project_name')
    # ### end Alembic commands ###
