"""update groups and group members tables

Revision ID: a040714620c1
Revises: c3d2f6b7a9e1
Create Date: 2026-05-18 14:52:29.868725

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a040714620c1'
down_revision: Union[str, Sequence[str], None] = 'c3d2f6b7a9e1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('group_members', sa.Column('note', sa.String(), nullable=True))
    op.alter_column('group_members', 'group_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('group_members', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('group_members', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('true'))
    op.add_column('groups', sa.Column('group_code', sa.String(), nullable=False))
    op.add_column('groups', sa.Column('profile_pic', sa.String(), nullable=True))
    op.alter_column('groups', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('true'))
    op.create_unique_constraint(None, 'groups', ['group_code'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'groups', type_='unique')
    op.alter_column('groups', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('true'))
    op.drop_column('groups', 'profile_pic')
    op.drop_column('groups', 'group_code')
    op.alter_column('group_members', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('true'))
    op.alter_column('group_members', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('group_members', 'group_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('group_members', 'note')
    # ### end Alembic commands ###
