"""add group id in tasks

Revision ID: c371f0993dfd
Revises: 2aaa66fe1491
Create Date: 2026-05-19 19:54:00.972800

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c371f0993dfd'
down_revision: Union[str, Sequence[str], None] = '2aaa66fe1491'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('group_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'tasks', 'groups', ['group_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tasks', type_='foreignkey')
    op.drop_column('tasks', 'group_id')
    # ### end Alembic commands ###
